create table if not exists public.appointment_events (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null references public.appointments(id) on delete cascade,
  actor_id uuid references public.users(id) on delete set null,
  event_type text not null,
  title text not null,
  body text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint appointment_events_type_check check (event_type in (
    'booking_requested',
    'booking_accepted',
    'booking_declined',
    'payment_submitted',
    'payment_verified',
    'payment_rejected',
    'payout_paid'
  ))
);

create index if not exists appointment_events_appointment_created_idx
  on public.appointment_events(appointment_id, created_at desc);

create index if not exists appointment_events_actor_idx
  on public.appointment_events(actor_id, created_at desc)
  where actor_id is not null;

create index if not exists appointment_events_type_idx
  on public.appointment_events(event_type, created_at desc);

alter table public.appointment_events enable row level security;

revoke all on table public.appointment_events from anon, authenticated;
grant select on table public.appointment_events to authenticated;
grant all on table public.appointment_events to service_role;
grant usage, select on sequence public.appointment_events_id_seq to service_role;

create or replace function private.create_appointment_event(
  p_appointment_id bigint,
  p_actor_id uuid,
  p_event_type text,
  p_title text,
  p_body text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
begin
  if p_appointment_id is null or nullif(trim(coalesce(p_event_type, '')), '') is null then
    return;
  end if;

  insert into public.appointment_events (
    appointment_id,
    actor_id,
    event_type,
    title,
    body,
    metadata
  ) values (
    p_appointment_id,
    p_actor_id,
    p_event_type,
    coalesce(nullif(trim(coalesce(p_title, '')), ''), p_event_type),
    coalesce(nullif(trim(coalesce(p_body, '')), ''), p_event_type),
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function private.handle_appointment_events()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  doctor_actor_id uuid;
  payment_was_submitted boolean;
  payment_is_submitted boolean;
  event_metadata jsonb;
begin
  select users.id into doctor_actor_id
  from public.users
  where users."doctorId" = new.doctor_id
  limit 1;

  event_metadata := jsonb_build_object(
    'appointment_id', new.id,
    'patient_name', new.patient_name,
    'doctor_name', new.doctor_name,
    'amount', new.amount,
    'slot', new.slot,
    'appointment_date', new.appointment_date,
    'status', new.status,
    'payment_status', new.payment_status,
    'payment_mode', new.payment_mode,
    'transaction_id', new.transaction_id,
    'payment_receiver_upi', new.payment_receiver_upi,
    'payment_rejection_reason', new.payment_rejection_reason,
    'payout_status', new.payout_status,
    'doctor_payout_amount', new.doctor_payout_amount,
    'platform_fee_amount', new.platform_fee_amount
  );

  if tg_op = 'INSERT' then
    perform private.create_appointment_event(
      new.id,
      new.patient_id,
      'booking_requested',
      'Booking requested',
      coalesce(new.patient_name, 'Patient') || ' requested ' || coalesce(new.slot, 'a slot') || ' with ' || coalesce(new.doctor_name, 'the doctor') || '.',
      event_metadata
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if old.status is distinct from new.status and new.status = 'Accepted' then
      perform private.create_appointment_event(
        new.id,
        doctor_actor_id,
        'booking_accepted',
        'Doctor accepted',
        coalesce(new.doctor_name, 'Doctor') || ' accepted the appointment. Payment can now be submitted.',
        event_metadata
      );
    end if;

    if old.status is distinct from new.status and new.status = 'Cancelled' then
      perform private.create_appointment_event(
        new.id,
        doctor_actor_id,
        'booking_declined',
        'Doctor declined',
        coalesce(new.doctor_name, 'Doctor') || ' declined the appointment request.',
        event_metadata
      );
    end if;

    payment_was_submitted := coalesce(old.payment_status, 'Unpaid') in ('Payment Submitted', 'Pending Verification');
    payment_is_submitted := coalesce(new.payment_status, 'Unpaid') in ('Payment Submitted', 'Pending Verification');

    if not payment_was_submitted and payment_is_submitted then
      perform private.create_appointment_event(
        new.id,
        new.patient_id,
        'payment_submitted',
        'Payment proof submitted',
        coalesce(new.patient_name, 'Patient') || ' submitted ' || coalesce(new.payment_mode, 'payment') || ' proof' || case when new.transaction_id is not null then ' with UTR ' || new.transaction_id else '' end || '.',
        event_metadata
      );
    end if;

    if old.payment_status is distinct from new.payment_status and new.payment_status = 'Verified' then
      perform private.create_appointment_event(
        new.id,
        new.payment_verified_by,
        'payment_verified',
        'Payment verified',
        'Admin verified the payment and confirmed the appointment.',
        event_metadata
      );
    end if;

    if old.payment_status is distinct from new.payment_status and new.payment_status = 'Rejected' then
      perform private.create_appointment_event(
        new.id,
        new.payment_verified_by,
        'payment_rejected',
        'Payment proof rejected',
        coalesce(new.payment_rejection_reason, 'Admin rejected the payment proof.'),
        event_metadata
      );
    end if;

    if old.payout_status is distinct from new.payout_status and new.payout_status = 'Paid' then
      perform private.create_appointment_event(
        new.id,
        new.payout_marked_by,
        'payout_paid',
        'Payout marked paid',
        'Admin marked the doctor payout paid for appointment #' || new.id::text || '.',
        event_metadata
      );
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists appointment_events_audit_trigger on public.appointments;
create trigger appointment_events_audit_trigger
after insert or update on public.appointments
for each row execute function private.handle_appointment_events();

revoke all on function private.create_appointment_event(bigint, uuid, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function private.handle_appointment_events() from public, anon, authenticated;

drop policy if exists "Appointment participants can read event trail" on public.appointment_events;
create policy "Appointment participants can read event trail"
  on public.appointment_events
  for select
  to authenticated
  using (
    (select private.is_admin())
    or exists (
      select 1
      from public.appointments
      where appointments.id = appointment_events.appointment_id
        and (
          appointments.patient_id = (select auth.uid())
          or appointments.doctor_id in (
            select users."doctorId"
            from public.users
            where users.id = (select auth.uid())
              and users."doctorId" is not null
          )
        )
    )
  );
