create table if not exists public.doctor_working_dates (
  id bigint generated by default as identity primary key,
  doctor_id bigint not null references public.doctors(id) on delete cascade,
  work_date date not null,
  slots text[] not null default array[]::text[],
  is_available boolean not null default true,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint doctor_working_dates_slots_required check (
    is_available is false or coalesce(cardinality(slots), 0) > 0
  ),
  constraint doctor_working_dates_unique unique (doctor_id, work_date)
);

create index if not exists doctor_working_dates_lookup_idx
  on public.doctor_working_dates (doctor_id, work_date)
  where is_available;

create or replace function public.set_doctor_working_dates_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists doctor_working_dates_set_updated_at on public.doctor_working_dates;
create trigger doctor_working_dates_set_updated_at
  before update on public.doctor_working_dates
  for each row
  execute function public.set_doctor_working_dates_updated_at();

alter table public.doctor_working_dates enable row level security;

revoke all on table public.doctor_working_dates from public, anon, authenticated;
grant select on table public.doctor_working_dates to anon;
grant select, insert, update, delete on table public.doctor_working_dates to authenticated;
grant all on table public.doctor_working_dates to service_role;
grant usage, select on sequence public.doctor_working_dates_id_seq to authenticated, service_role;

drop policy if exists "Available working dates are readable" on public.doctor_working_dates;
create policy "Available working dates are readable"
  on public.doctor_working_dates
  for select
  to anon, authenticated
  using (
    (
      is_available
      and exists (
        select 1
        from public.doctors
        where doctors.id = doctor_working_dates.doctor_id
          and coalesce(doctors.verification_status, 'pending') = 'approved'
      )
    )
    or private.is_admin()
    or exists (
      select 1
      from public.doctors
      where doctors.id = doctor_working_dates.doctor_id
        and (
          doctors.owner_id = (select auth.uid())
          or doctors.id in (
            select users."doctorId"
            from public.users
            where users.id = (select auth.uid())
          )
        )
    )
  );

drop policy if exists "Doctors can insert own working dates" on public.doctor_working_dates;
create policy "Doctors can insert own working dates"
  on public.doctor_working_dates
  for insert
  to authenticated
  with check (
    private.is_admin()
    or exists (
      select 1
      from public.doctors
      where doctors.id = doctor_working_dates.doctor_id
        and (
          doctors.owner_id = (select auth.uid())
          or doctors.id in (
            select users."doctorId"
            from public.users
            where users.id = (select auth.uid())
          )
        )
    )
  );

drop policy if exists "Doctors can update own working dates" on public.doctor_working_dates;
create policy "Doctors can update own working dates"
  on public.doctor_working_dates
  for update
  to authenticated
  using (
    private.is_admin()
    or exists (
      select 1
      from public.doctors
      where doctors.id = doctor_working_dates.doctor_id
        and (
          doctors.owner_id = (select auth.uid())
          or doctors.id in (
            select users."doctorId"
            from public.users
            where users.id = (select auth.uid())
          )
        )
    )
  )
  with check (
    private.is_admin()
    or exists (
      select 1
      from public.doctors
      where doctors.id = doctor_working_dates.doctor_id
        and (
          doctors.owner_id = (select auth.uid())
          or doctors.id in (
            select users."doctorId"
            from public.users
            where users.id = (select auth.uid())
          )
        )
    )
  );

drop policy if exists "Doctors can delete own working dates" on public.doctor_working_dates;
create policy "Doctors can delete own working dates"
  on public.doctor_working_dates
  for delete
  to authenticated
  using (
    private.is_admin()
    or exists (
      select 1
      from public.doctors
      where doctors.id = doctor_working_dates.doctor_id
        and (
          doctors.owner_id = (select auth.uid())
          or doctors.id in (
            select users."doctorId"
            from public.users
            where users.id = (select auth.uid())
          )
        )
    )
  );

create or replace function public.create_appointment_request(
  p_doctor_id bigint,
  p_slot text,
  p_appointment_date text default null
)
returns public.appointments
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  caller_id uuid := auth.uid();
  patient_profile public.users%rowtype;
  doctor_profile public.doctors%rowtype;
  normalized_slot text := nullif(trim(coalesce(p_slot, '')), '');
  requested_date text := coalesce(nullif(trim(coalesce(p_appointment_date, '')), ''), timezone('utc'::text, now())::date::text);
  requested_day text := left(requested_date, 10);
  requested_work_date date;
  available_slots text[];
  fee_amount numeric;
  created_appointment public.appointments%rowtype;
begin
  if caller_id is null then
    raise exception 'You must be signed in to book an appointment.';
  end if;

  if normalized_slot is null then
    raise exception 'Select a valid slot before booking.';
  end if;

  if requested_day !~ '^\d{4}-\d{2}-\d{2}$' then
    raise exception 'Select a valid appointment date.';
  end if;

  requested_work_date := requested_day::date;
  if requested_work_date < current_date then
    raise exception 'Select a current or future appointment date.';
  end if;

  select * into patient_profile
  from public.users
  where users.id = caller_id;

  if not found then
    raise exception 'Patient profile was not found.';
  end if;

  if coalesce(patient_profile.role, 'patient') <> 'patient' then
    raise exception 'Only patients can book appointments.';
  end if;

  select * into doctor_profile
  from public.doctors
  where doctors.id = p_doctor_id;

  if not found then
    raise exception 'Doctor was not found.';
  end if;

  if coalesce(doctor_profile.verification_status, 'pending') <> 'approved' then
    raise exception 'This provider is not available for booking yet.';
  end if;

  select doctor_working_dates.slots into available_slots
  from public.doctor_working_dates
  where doctor_working_dates.doctor_id = doctor_profile.id
    and doctor_working_dates.work_date = requested_work_date
    and doctor_working_dates.is_available
  limit 1;

  if coalesce(cardinality(available_slots), 0) = 0 then
    raise exception 'This provider is not taking appointments on this date.';
  end if;

  if not exists (
    select 1
    from unnest(available_slots) as available_slot(slot_value)
    where lower(trim(available_slot.slot_value)) = lower(normalized_slot)
  ) then
    raise exception 'This appointment time is not available for the selected date.';
  end if;

  fee_amount := public.money_amount(doctor_profile.price);
  if fee_amount <= 0 then
    raise exception 'Doctor fee is not configured.';
  end if;

  if exists (
    select 1
    from public.appointments
    where appointments.doctor_id = doctor_profile.id
      and appointments.appointment_day = requested_day
      and lower(trim(appointments.slot)) = lower(normalized_slot)
      and appointments.status in ('Pending Approval', 'Accepted', 'Confirmed')
  ) then
    raise exception 'This slot is already booked or waiting for approval. Please choose another time.';
  end if;

  perform set_config('request.raphal_booking_rpc', 'create_appointment_request', true);

  insert into public.appointments (
    patient_id,
    doctor_id,
    doctor_name,
    patient_name,
    slot,
    appointment_date,
    status,
    payment_status,
    amount
  ) values (
    caller_id,
    doctor_profile.id,
    doctor_profile.name,
    coalesce(patient_profile.name, 'Patient'),
    normalized_slot,
    requested_day,
    'Pending Approval',
    'Unpaid',
    'Rs. ' || trim(to_char(fee_amount, 'FM9999999990.00'))
  ) returning * into created_appointment;

  return created_appointment;
exception
  when unique_violation then
    raise exception 'This slot is already booked or waiting for approval. Please choose another time.';
end;
$$;

drop policy if exists "Patients can create appointments" on public.appointments;
create policy "Patients can create appointments"
  on public.appointments
  for insert
  to authenticated
  with check (
    (select current_setting('request.raphal_booking_rpc', true)) = 'create_appointment_request'
    and patient_id = (select auth.uid())
    and coalesce(status, 'Pending Approval') = 'Pending Approval'
    and coalesce(payment_status, 'Unpaid') = 'Unpaid'
    and payment_mode is null
    and nullif(trim(coalesce(transaction_id, '')), '') is null
    and payment_submitted_at is null
    and payment_receiver_upi is null
    and payment_verified_at is null
    and payment_verified_by is null
    and payment_rejection_reason is null
    and coalesce(payout_status, 'Not Due') = 'Not Due'
    and payout_marked_at is null
    and payout_marked_by is null
    and admin_notes is null
    and doctor_payout_amount is null
    and coalesce(platform_fee_amount, 0) = 0
    and coalesce(is_paid_out, false) is false
    and appointment_day ~ '^\d{4}-\d{2}-\d{2}$'
    and public.money_amount(amount) > 0
    and public.money_amount(amount) = public.money_amount((select doctors.price from public.doctors where doctors.id = doctor_id))
    and coalesce(doctor_name, '') = coalesce((select doctors.name from public.doctors where doctors.id = doctor_id), '')
    and coalesce(patient_name, 'Patient') = coalesce((select nullif(users.name, '') from public.users where users.id = (select auth.uid())), 'Patient')
    and exists (
      select 1
      from public.doctor_working_dates
      where doctor_working_dates.doctor_id = appointments.doctor_id
        and doctor_working_dates.work_date::text = appointments.appointment_day
        and doctor_working_dates.is_available
        and exists (
          select 1
          from unnest(doctor_working_dates.slots) as available_slot(slot_value)
          where lower(trim(available_slot.slot_value)) = lower(trim(appointments.slot))
        )
    )
    and coalesce((select doctors.verification_status from public.doctors where doctors.id = doctor_id), 'pending') = 'approved'
  );

drop policy if exists "Appointment workflow RPCs can update appointment states" on public.appointments;
create policy "Appointment workflow RPCs can update appointment states"
  on public.appointments
  for update
  to authenticated
  using (
    private.is_admin()
    or (
      patient_id = (select auth.uid())
      and status = 'Accepted'
      and coalesce(payment_status, 'Unpaid') = any (array['Unpaid'::text, 'Rejected'::text])
    )
    or (
      status = 'Pending Approval'
      and doctor_id in (select users."doctorId" from public.users where users.id = (select auth.uid()))
    )
  )
  with check (
    (select current_setting('request.raphal_workflow_rpc', true)) = any (array[
      'doctor_decide_appointment',
      'submit_appointment_payment',
      'admin_verify_payment',
      'admin_reject_payment',
      'admin_mark_payout_paid'
    ])
    and (
      private.is_admin()
      or (
        patient_id = (select auth.uid())
        and status = 'Accepted'
        and payment_status = 'Payment Submitted'
        and payment_mode = any (array['UPI'::text, 'Cash'::text])
        and (
          (
            payment_mode = 'Cash'
            and transaction_id is null
            and payment_receiver_upi = 'Cash at clinic'
          )
          or (
            payment_mode = 'UPI'
            and nullif(trim(transaction_id), '') is not null
            and nullif(trim(payment_receiver_upi), '') is not null
          )
        )
        and payment_verified_at is null
        and payment_verified_by is null
        and payment_rejection_reason is null
        and coalesce(payout_status, 'Not Due') = 'Not Due'
        and payout_marked_at is null
        and payout_marked_by is null
        and admin_notes is null
        and doctor_payout_amount is null
        and coalesce(platform_fee_amount, 0) = 0
        and coalesce(is_paid_out, false) is false
        and public.money_amount(amount) > 0
        and public.money_amount(amount) = public.money_amount((select doctors.price from public.doctors where doctors.id = doctor_id))
        and coalesce(doctor_name, '') = coalesce((select doctors.name from public.doctors where doctors.id = doctor_id), '')
        and coalesce(patient_name, 'Patient') = coalesce((select nullif(users.name, '') from public.users where users.id = (select auth.uid())), 'Patient')
      )
      or (
        doctor_id in (select users."doctorId" from public.users where users.id = (select auth.uid()))
        and status = any (array['Accepted'::text, 'Cancelled'::text])
        and coalesce(payment_status, 'Unpaid') = 'Unpaid'
        and payment_mode is null
        and nullif(trim(coalesce(transaction_id, '')), '') is null
        and payment_submitted_at is null
        and payment_receiver_upi is null
        and payment_verified_at is null
        and payment_verified_by is null
        and payment_rejection_reason is null
        and coalesce(payout_status, 'Not Due') = 'Not Due'
        and payout_marked_at is null
        and payout_marked_by is null
        and admin_notes is null
        and doctor_payout_amount is null
        and coalesce(platform_fee_amount, 0) = 0
        and coalesce(is_paid_out, false) is false
      )
    )
  );

revoke execute on function public.create_appointment_request(bigint, text, text) from public, anon;
grant execute on function public.create_appointment_request(bigint, text, text) to authenticated, service_role;
