create extension if not exists pgcrypto;

create schema if not exists private;

create table if not exists public.doctors (
  id bigint generated by default as identity primary key,
  name text,
  specialty text,
  rating numeric default 5.0,
  reviews integer default 0,
  image text,
  district text,
  clinic_name text,
  location text,
  experience text,
  bio text,
  price text,
  upi_id text,
  push_token text,
  slots text[] default array['09:00 AM'::text, '10:00 AM'::text, '11:00 AM'::text, '02:00 PM'::text, '03:00 PM'::text],
  created_at timestamp with time zone default timezone('utc'::text, now()),
  owner_id uuid references auth.users(id) on delete set null
);

create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  password text,
  role text default 'patient',
  name text,
  phone text,
  address text,
  blood_group text default 'O+',
  allergies text,
  district text,
  push_token text,
  "doctorId" bigint references public.doctors(id),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_id uuid references public.users(id),
  doctor_id bigint references public.doctors(id),
  doctor_name text,
  patient_name text,
  slot text,
  appointment_date text,
  status text default 'Pending Approval',
  payment_status text default 'Unpaid',
  payment_mode text,
  transaction_id text,
  amount text,
  is_paid_out boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  payment_submitted_at timestamp with time zone,
  payment_receiver_upi text,
  payment_verified_at timestamp with time zone,
  payment_verified_by uuid references public.users(id) on delete set null,
  payment_rejection_reason text,
  payout_status text not null default 'Not Due',
  payout_marked_at timestamp with time zone,
  payout_marked_by uuid references public.users(id) on delete set null,
  admin_notes text,
  doctor_payout_amount numeric,
  platform_fee_amount numeric default 0,
  constraint appointments_status_valid check (status is null or status = any (array['Pending Approval'::text, 'Accepted'::text, 'Cancelled'::text, 'Confirmed'::text])),
  constraint appointments_payment_status_valid check (payment_status is null or payment_status = any (array['Unpaid'::text, 'Payment Submitted'::text, 'Pending Verification'::text, 'Verified'::text, 'Rejected'::text])),
  constraint appointments_payment_mode_valid check (payment_mode is null or payment_mode = any (array['UPI'::text, 'Cash'::text])),
  constraint appointments_payout_status_valid check (payout_status = any (array['Not Due'::text, 'Due'::text, 'Paid'::text, 'Hold'::text]))
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.users(id) on delete cascade,
  actor_id uuid references public.users(id) on delete set null,
  appointment_id bigint references public.appointments(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint notifications_type_valid check (type = any (array[
    'booking_requested'::text,
    'booking_accepted'::text,
    'booking_declined'::text,
    'payment_submitted'::text,
    'payment_verified'::text,
    'payment_rejected'::text,
    'payout_paid'::text
  ]))
);

create index if not exists doctors_owner_id_idx on public.doctors(owner_id);
create index if not exists users_doctor_id_idx on public.users("doctorId");
create index if not exists appointments_patient_id_idx on public.appointments(patient_id);
create index if not exists appointments_doctor_id_idx on public.appointments(doctor_id);
create index if not exists appointments_created_at_idx on public.appointments(created_at desc);
create index if not exists appointments_payment_status_idx on public.appointments(payment_status, status);
create index if not exists appointments_doctor_payout_idx on public.appointments(doctor_id, payout_status, is_paid_out);
create index if not exists appointments_payment_verified_by_idx on public.appointments(payment_verified_by);
create index if not exists appointments_payout_marked_by_idx on public.appointments(payout_marked_by);
create index if not exists notifications_recipient_created_idx on public.notifications(recipient_id, created_at desc);
create index if not exists notifications_unread_idx on public.notifications(recipient_id, read_at) where read_at is null;
create index if not exists notifications_appointment_idx on public.notifications(appointment_id);
create index if not exists notifications_actor_idx on public.notifications(actor_id);

alter table public.doctors enable row level security;
alter table public.users enable row level security;
alter table public.appointments enable row level security;
alter table public.notifications enable row level security;

revoke all on table public.doctors from anon, authenticated;
revoke all on table public.users from anon, authenticated;
revoke all on table public.appointments from anon, authenticated;
revoke all on table public.notifications from anon, authenticated;

grant select on table public.doctors to anon;
grant select, insert, update on table public.doctors to authenticated;
grant select, insert, update on table public.users to authenticated;
grant select, insert, update on table public.appointments to authenticated;
grant select, update on table public.notifications to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users
    where users.id = auth.uid()
      and users.role = 'admin'
  );
$$;

drop policy if exists "Doctors are publicly readable" on public.doctors;
create policy "Doctors are publicly readable"
  on public.doctors
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated doctors can create profile" on public.doctors;
create policy "Authenticated doctors can create profile"
  on public.doctors
  for insert
  to authenticated
  with check (owner_id = (select auth.uid()));

drop policy if exists "Users can update permitted doctors" on public.doctors;
create policy "Users can update permitted doctors"
  on public.doctors
  for update
  to authenticated
  using (
    private.is_admin()
    or owner_id = (select auth.uid())
    or id in (select users."doctorId" from public.users where users.id = (select auth.uid()))
  )
  with check (
    private.is_admin()
    or owner_id = (select auth.uid())
    or id in (select users."doctorId" from public.users where users.id = (select auth.uid()))
  );

drop policy if exists "Users can create own profile" on public.users;
create policy "Users can create own profile"
  on public.users
  for insert
  to authenticated
  with check (
    id = (select auth.uid())
    and coalesce(role, 'patient') = any (array['patient'::text, 'doctor'::text])
  );

drop policy if exists "Users can read permitted profiles" on public.users;
create policy "Users can read permitted profiles"
  on public.users
  for select
  to authenticated
  using (id = (select auth.uid()) or private.is_admin());

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
  on public.users
  for update
  to authenticated
  using (id = (select auth.uid()))
  with check (
    id = (select auth.uid())
    and coalesce(role, 'patient') = any (array['patient'::text, 'doctor'::text])
  );

drop policy if exists "Users can read permitted appointments" on public.appointments;
create policy "Users can read permitted appointments"
  on public.appointments
  for select
  to authenticated
  using (
    private.is_admin()
    or patient_id = (select auth.uid())
    or doctor_id in (select users."doctorId" from public.users where users.id = (select auth.uid()))
  );

drop policy if exists "Users can update permitted appointment states" on public.appointments;
create policy "Users can update permitted appointment states"
  on public.appointments
  for update
  to authenticated
  using (
    private.is_admin()
    or (
      patient_id = (select auth.uid())
      and status = 'Accepted'
      and coalesce(payment_status, 'Unpaid') = any (array['Unpaid'::text, 'Rejected'::text])
    )
    or (
      status = 'Pending Approval'
      and doctor_id in (select users."doctorId" from public.users where users.id = (select auth.uid()))
    )
  )
  with check (
    private.is_admin()
    or (
      patient_id = (select auth.uid())
      and status = 'Accepted'
      and payment_status = any (array['Payment Submitted'::text, 'Pending Verification'::text])
      and payment_mode = any (array['UPI'::text, 'Cash'::text])
      and (payment_mode = 'Cash' or nullif(trim(transaction_id), '') is not null)
    )
    or (
      doctor_id in (select users."doctorId" from public.users where users.id = (select auth.uid()))
      and status = any (array['Accepted'::text, 'Cancelled'::text])
      and coalesce(payment_status, 'Unpaid') = 'Unpaid'
    )
  );

drop policy if exists "Users can read own notifications" on public.notifications;
create policy "Users can read own notifications"
  on public.notifications
  for select
  to authenticated
  using (recipient_id = (select auth.uid()));

drop policy if exists "Users can update own notifications" on public.notifications;
create policy "Users can update own notifications"
  on public.notifications
  for update
  to authenticated
  using (recipient_id = (select auth.uid()))
  with check (recipient_id = (select auth.uid()));

create or replace function private.create_notification(
  p_recipient_id uuid,
  p_actor_id uuid,
  p_appointment_id bigint,
  p_type text,
  p_title text,
  p_body text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if p_recipient_id is null then
    return;
  end if;

  insert into public.notifications (
    recipient_id,
    actor_id,
    appointment_id,
    type,
    title,
    body,
    metadata
  ) values (
    p_recipient_id,
    p_actor_id,
    p_appointment_id,
    p_type,
    p_title,
    p_body,
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function private.notify_admins(
  p_actor_id uuid,
  p_appointment_id bigint,
  p_type text,
  p_title text,
  p_body text,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
declare
  admin_row record;
begin
  for admin_row in select id from public.users where role = 'admin' loop
    perform private.create_notification(
      admin_row.id,
      p_actor_id,
      p_appointment_id,
      p_type,
      p_title,
      p_body,
      p_metadata
    );
  end loop;
end;
$$;

create or replace function private.handle_appointment_notifications()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
declare
  doctor_user_id uuid;
  doctor_owner_id uuid;
  doctor_recipient uuid;
  payment_was_submitted boolean;
  payment_is_submitted boolean;
  metadata jsonb;
begin
  select users.id into doctor_user_id
  from public.users
  where users."doctorId" = new.doctor_id
  limit 1;

  select doctors.owner_id into doctor_owner_id
  from public.doctors
  where doctors.id = new.doctor_id
  limit 1;

  doctor_recipient := coalesce(doctor_user_id, doctor_owner_id);
  metadata := jsonb_build_object(
    'appointment_id', new.id,
    'patient_name', new.patient_name,
    'doctor_name', new.doctor_name,
    'amount', new.amount,
    'slot', new.slot,
    'appointment_date', new.appointment_date,
    'payment_status', new.payment_status,
    'status', new.status,
    'transaction_id', new.transaction_id,
    'payment_receiver_upi', new.payment_receiver_upi,
    'payout_status', new.payout_status,
    'doctor_payout_amount', new.doctor_payout_amount,
    'platform_fee_amount', new.platform_fee_amount
  );

  if tg_op = 'INSERT' then
    perform private.create_notification(
      doctor_recipient,
      new.patient_id,
      new.id,
      'booking_requested',
      'New booking request',
      coalesce(new.patient_name, 'A patient') || ' requested an appointment for ' || coalesce(new.slot, 'the selected slot') || '.',
      metadata
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if old.status is distinct from new.status and new.status = 'Accepted' then
      perform private.create_notification(
        new.patient_id,
        doctor_recipient,
        new.id,
        'booking_accepted',
        'Doctor accepted your booking',
        'Your doctor accepted the request. Pay by UPI and submit the UTR to confirm.',
        metadata
      );
    end if;

    if old.status is distinct from new.status and new.status = 'Cancelled' then
      perform private.create_notification(
        new.patient_id,
        doctor_recipient,
        new.id,
        'booking_declined',
        'Booking declined',
        'The doctor declined this request. You can book another slot or choose a different specialist.',
        metadata
      );
    end if;

    payment_was_submitted := coalesce(old.payment_status, 'Unpaid') in ('Payment Submitted', 'Pending Verification');
    payment_is_submitted := coalesce(new.payment_status, 'Unpaid') in ('Payment Submitted', 'Pending Verification');

    if not payment_was_submitted and payment_is_submitted then
      perform private.notify_admins(
        new.patient_id,
        new.id,
        'payment_submitted',
        'Payment proof submitted',
        coalesce(new.patient_name, 'A patient') || ' submitted ' || coalesce(new.payment_mode, 'payment') || ' proof' || case when new.transaction_id is not null then ' with UTR ' || new.transaction_id else '' end || '.',
        metadata
      );
      perform private.create_notification(
        doctor_recipient,
        new.patient_id,
        new.id,
        'payment_submitted',
        'Payment proof submitted',
        coalesce(new.patient_name, 'A patient') || ' submitted payment proof. Admin verification is pending.',
        metadata
      );
    end if;

    if old.payment_status is distinct from new.payment_status and new.payment_status = 'Verified' then
      perform private.create_notification(
        new.patient_id,
        new.payment_verified_by,
        new.id,
        'payment_verified',
        'Booking confirmed',
        'Admin verified your payment. Your appointment is confirmed.',
        metadata
      );
      perform private.create_notification(
        doctor_recipient,
        new.payment_verified_by,
        new.id,
        'payment_verified',
        'Payment verified',
        'Admin verified payment for ' || coalesce(new.patient_name, 'the patient') || '.',
        metadata
      );
    end if;

    if old.payment_status is distinct from new.payment_status and new.payment_status = 'Rejected' then
      perform private.create_notification(
        new.patient_id,
        new.payment_verified_by,
        new.id,
        'payment_rejected',
        'Payment proof needs correction',
        coalesce(new.payment_rejection_reason, 'Please recheck and submit the UTR again.'),
        metadata
      );
    end if;

    if old.payout_status is distinct from new.payout_status and new.payout_status = 'Paid' then
      perform private.create_notification(
        doctor_recipient,
        new.payout_marked_by,
        new.id,
        'payout_paid',
        'Payout marked paid',
        'Admin marked payout paid for appointment #' || new.id::text || '.',
        metadata || jsonb_build_object('doctor_payout_amount', new.doctor_payout_amount)
      );
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists appointment_notifications_trigger on public.appointments;
create trigger appointment_notifications_trigger
after insert or update on public.appointments
for each row execute function private.handle_appointment_notifications();

revoke all on function private.is_admin() from public, anon, authenticated;
revoke all on function private.create_notification(uuid, uuid, bigint, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function private.notify_admins(uuid, bigint, text, text, text, jsonb) from public, anon, authenticated;
revoke all on function private.handle_appointment_notifications() from public, anon, authenticated;

create table if not exists public.device_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  token text not null,
  platform text not null default 'android',
  device_id text,
  enabled boolean not null default true,
  last_seen_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint device_tokens_platform_check check (platform in ('android', 'ios', 'web')),
  constraint device_tokens_token_nonempty check (length(trim(token)) > 0)
);

create unique index if not exists device_tokens_token_key on public.device_tokens(token);
create index if not exists device_tokens_user_idx on public.device_tokens(user_id, enabled, last_seen_at desc);
create index if not exists device_tokens_device_idx on public.device_tokens(user_id, device_id) where device_id is not null;

alter table public.device_tokens enable row level security;

revoke all on table public.device_tokens from anon, authenticated;
grant select, insert, update, delete on table public.device_tokens to authenticated;
grant usage, select on sequence public.device_tokens_id_seq to authenticated;

drop policy if exists "Users can read own device tokens" on public.device_tokens;
drop policy if exists "Users can insert own device tokens" on public.device_tokens;
drop policy if exists "Users can update own device tokens" on public.device_tokens;
drop policy if exists "Users can delete own device tokens" on public.device_tokens;

create policy "Users can read own device tokens"
  on public.device_tokens
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Users can insert own device tokens"
  on public.device_tokens
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Users can update own device tokens"
  on public.device_tokens
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own device tokens"
  on public.device_tokens
  for delete
  to authenticated
  using (auth.uid() = user_id);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.notifications(id) on delete cascade,
  recipient_id uuid not null references public.users(id) on delete cascade,
  device_token_id bigint references public.device_tokens(id) on delete set null,
  token text not null,
  status text not null default 'pending',
  attempt_count integer not null default 0,
  last_error text,
  last_attempted_at timestamp with time zone,
  sent_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint notification_deliveries_status_check check (status in ('pending', 'processing', 'sent', 'failed', 'skipped')),
  constraint notification_deliveries_attempt_count_check check (attempt_count >= 0),
  constraint notification_deliveries_token_nonempty check (length(trim(token)) > 0),
  constraint notification_deliveries_notification_device_unique unique (notification_id, device_token_id)
);

create index if not exists notification_deliveries_status_idx on public.notification_deliveries(status, created_at) where status in ('pending', 'processing');
create index if not exists notification_deliveries_recipient_idx on public.notification_deliveries(recipient_id, created_at desc);
create index if not exists notification_deliveries_notification_idx on public.notification_deliveries(notification_id);

alter table public.notification_deliveries enable row level security;

revoke all on table public.notification_deliveries from anon, authenticated;
grant select on table public.notification_deliveries to authenticated;

drop policy if exists "Users can read own push deliveries" on public.notification_deliveries;
drop policy if exists "Admins can read push deliveries" on public.notification_deliveries;

create policy "Users can read own push deliveries"
  on public.notification_deliveries
  for select
  to authenticated
  using (auth.uid() = recipient_id);

create policy "Admins can read push deliveries"
  on public.notification_deliveries
  for select
  to authenticated
  using (private.is_admin());

insert into public.device_tokens (user_id, token, platform, enabled, last_seen_at, updated_at)
select id, push_token, 'android', true, timezone('utc'::text, now()), timezone('utc'::text, now())
from public.users
where push_token is not null
  and length(trim(push_token)) > 0
on conflict (token) do update set
  user_id = excluded.user_id,
  enabled = true,
  last_seen_at = excluded.last_seen_at,
  updated_at = excluded.updated_at;

create or replace function private.enqueue_notification_deliveries()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
begin
  insert into public.notification_deliveries (notification_id, recipient_id, device_token_id, token)
  select new.id, new.recipient_id, device_tokens.id, device_tokens.token
  from public.device_tokens
  where device_tokens.user_id = new.recipient_id
    and device_tokens.enabled is true
  on conflict (notification_id, device_token_id) do nothing;

  return new;
end;
$$;

drop trigger if exists notification_push_delivery_trigger on public.notifications;
create trigger notification_push_delivery_trigger
after insert on public.notifications
for each row execute function private.enqueue_notification_deliveries();
